# Generated by Django 4.0.6 on 2022-07-16 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='webfiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'xml', 'json'])])),
            ],
        ),
    ]
