# Generated by Django 4.0.6 on 2022-07-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='category',
            field=models.CharField(choices=[('pd', 'pdf'), ('jp', 'jpg'), ('xm', 'xml'), ('js', 'json')], default='pdf', max_length=2),
            preserve_default=False,
        ),
    ]
