# Generated by Django 4.0.6 on 2022-07-16 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadfiles_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='XmlToDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('xmlFile', models.FileField(upload_to='xmlFiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])])),
            ],
        ),
    ]
