# Generated by Django 4.0.6 on 2022-07-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_xmltodict'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='josnReady')),
            ],
        ),
    ]
