# Generated by Django 4.0.6 on 2022-07-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_storejson'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmltodict',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='storejson',
            name='file',
            field=models.FileField(upload_to='jsonReady/'),
        ),
    ]
